### ISSUE TITLE
RNG Chance Error via 'Second Step'

### ISSUE THREAD

**Issue by AstralFS** [finnboy84360/Fineboy#1]
When '**first step**' is complete and '**second step**' begins, the lack of talking causes those around my immediate area to feel uneasy and often consider me to be 'not fine'. Continuing with the '**third step**' further adds to this issue with an end result of:

> ERROR: Not Fine.

May I suggest modifying the second step to improve chances of achieving Finemanship?

Thank you.

**Comment by finnboy84360** [comment]
you don't have to talk when is not something you can express on it but if someone ask your opinon on something, you can express it but like the first step, don't try to piss off people

**Comment by AstralFS** [comment]
Okay, this seems to resolve the issue! Thanks again!
